### ISSUE TITLE
Define Query responses - requires YAML knowledge

### ISSUE THREAD

**Issue by rggibb** [opengeospatial/ogcapi-discrete-global-grid-systems#23]
responses are:

     Distance: real + uom.asString .. uom can just be a string, but ifa OGC compliant uom has been defined then lets use it

      Boolean: True|False

      RelativePosition: enum,eration with possible values of:
      {Before, After, Meets, MetBy, Overlaps, OverlappedBy, Starts, StartedBy, 
           During, Contains, Finishes, FinishedBy, Equals, In, Disjoint}

**Comment by rggibb** [comment]
Boolean and relativePosition defined as schemas and used in response definitions and in parameter defenitions

**Comment by rggibb** [comment]
Distance: actually a tad more complex. Since we are supporting up to 4D DGGS, so Distance can be spatial, temporal or spatio-temporal, so it needs to be an array of a [spatialDist,temporalDist] and each of spatialDist and temporalDist need to be comrpised of both a number and a uom, where uom is selected from a spatial uom enumerated list and a temporal uom enumerated list. To be a valid list at least one of spatialDist and temporalDist must be present, otherwise it is a null distance

So this needs a bit more work to determine best the YAML structure, and to locate spatial and temporal enum lists of uom, and see if they are already implemented somewhere or where they should be defined.

I suggest we stick to non-Gregorian calendar temporal distances, ie restrict the input to decimal fractional s, m, h, d, y etc.

**Comment by jerstlouis** [comment]
This issue has been obsoleted by event, as the latest API focuses on zone data retrieval and zone query, and no longer implements operations like distances between two zones or zone and geometry (which the clients can perform themselves with an offline DGGS software library).

However, the zone query functionality at `/zones` will return the list of zones where data is available (or is matched by a particular CQL2 query), and the client can then check for zones in the response.
