### ISSUE TITLE
Update the example /conformance response to include the URI of the DGGS API's Core Conformance Class

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-discrete-global-grid-systems#43]
Currently the example response of the `/conformance` resource in v0.0.6 of the DGGS API OpenAPI definition document returns this example value:

```json
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/html",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-features-1/1.1/conf/geojson"
  ]
}
```

It should be updated to include the URI of the DGGS API's Core Conformance Class (i.e. http://www.opengis.net/spec/ogcapi-dggs-1/1.0/conf/core).

**Comment by jerstlouis** [comment]
@ghobona Thanks for reporting this issue, and sorry for the 3 years delay in responding. 
onfirming that the DGGS API Core Conformance class is now included:

https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/blob/master/openapi/responses/common-core/rConformance.yaml#L15

Also confirmed that this is working properly on the SwaggerUI:

https://petstore.swagger.io/?url=https://raw.githubusercontent.com/opengeospatial/ogcapi-discrete-global-grid-systems/master/openapi/ogcapi-dggs-1.bundled.json#/Conformance/getConformance

Therefore, closing this issue.
