### ISSUE TITLE
Duplicate of zone-geojson

### ISSUE THREAD

**Issue by gbuehler** [opengeospatial/ogcapi-discrete-global-grid-systems#70]
I am getting an error when building the document:

Modspec identifier http://www.opengis.net/spec/ogcapi-dggs-1/1.0/req/zone-geojson is used more than once

I believe that:

[core/requirements/requirements_class_zone_list_fgjson.adoc](https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/blob/master/core/requirements/requirements_class_zone_list_fgjson.adoc)

should have the identifier listed as zone-fgjson and the inherit changed from RFC7946.

**Comment by jerstlouis** [comment]
Thanks @gbuehler! I'm curious, was this a fatal error for the auto-generation?
I didn't even seem to see that error here and the document seemed to generate fine before the fix...
Is there somewhere where we can see those auto-generation failures / reasons?

**Comment by gbuehler** [comment]
@jerstlouis This was/is a fatal error in the Master of this repo.  Will you be merging your update with the Master?

**Comment by jerstlouis** [comment]
@gbuehler oops, sorry, thought I did. Fixed.

I am really confused about it being a fatal error but the document having been updated and also working locally :)

**Comment by gbuehler** [comment]
@jerstlouis I just did a new clone of the repo, both on my Mac and on a Linux machine.  I got the latest version of Metanorma docker instance and I now get different errors, but it still will not build:

/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node.rb:1496:in `coerce'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node.rb:149:in `add_child'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node.rb:257:in `<<'
/usr/local/bundle/gems/mn-requirements-0.3.6/lib/metanorma/modspec/table_cleanup.rb:101:in `block in expand_xrefs_in_reqt'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
/usr/local/bundle/gems/mn-requirements-0.3.6/lib/metanorma/modspec/table_cleanup.rb:100:in `expand_xrefs_in_reqt'
/usr/local/bundle/gems/mn-requirements-0.3.6/lib/metanorma/modspec/table_cleanup.rb:107:in `truncate_id_base_in_reqt'
/usr/local/bundle/gems/mn-requirements-0.3.6/lib/metanorma/modspec/table_cleanup.rb:10:in `requirement_table_cleanup'
/usr/local/bundle/gems/mn-requirements-0.3.6/lib/metanorma/modspec/isodoc.rb:11:in `requirement_render1'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_function/reqt.rb:44:in `requirement_render1'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_function/reqt.rb:39:in `block in requirement_render'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
/usr/local/bundle/gems/nokogiri-1.15.6-aarch64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_function/reqt.rb:39:in `requirement_render'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_xml_convert.rb:81:in `block'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_xml_convert.rb:43:in `conversions'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/presentation_xml_convert.rb:25:in `convert1'
/usr/local/bundle/gems/metanorma-ogc-2.5.7/lib/isodoc/ogc/presentation_xml_convert.rb:15:in `convert1'
/usr/local/bundle/gems/isodoc-2.10.1/lib/isodoc/convert.rb:168:in `convert'
/usr/local/bundle/gems/metanorma-ogc-2.5.7/lib/metanorma/ogc/processor.rb:52:in `output'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:183:in `process_output_unthreaded'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:169:in `process_exts1'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:143:in `process_ext'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:125:in `block in process_exts_run'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:124:in `each'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:124:in `process_exts_run'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:119:in `process_exts'
/usr/local/bundle/gems/metanorma-1.7.6/lib/metanorma/compile.rb:35:in `compile'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/compiler.rb:30:in `compile'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/compiler.rb:35:in `compile'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/command.rb:244:in `compile_document'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/command.rb:48:in `block in compile'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/command.rb:48:in `each'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli/command.rb:48:in `compile'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/metanorma-cli-1.9.7/lib/metanorma/cli.rb:34:in `start'
/usr/local/bundle/gems/metanorma-cli-1.9.7/exe/metanorma:25:in `block in <top (required)>'
/usr/local/bundle/gems/metanorma-cli-1.9.7/exe/metanorma:43:in `<top (required)>'
/usr/local/bundle/bin/metanorma:25:in `load'
/usr/local/bundle/bin/metanorma:25:in `<main>'
Requires a Node, NodeSet or String argument, and cannot accept a NilClass.
(You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)

**Comment by gbuehler** [comment]
@jerstlouis 

I am not able to get the document to build past clause_13_encodings.adoc

For example, in requirements_class_zone_list_geotiff.adoc, there is a link: 
`inherit:: <<TIFF_V6>>`

I believe the build fails because there is no anchor for it.

If I remove the above line <<TIFF_V6>>, it does build.

Here are all the includes that have such undefined anchors and if commented out, allow the build to work:

```
include::../requirements/requirements_class_zone_data_geotiff.adoc[]
include::../requirements/requirements_class_zone_data_fgjson.adoc[]
include::../requirements/requirements_class_zone_data_coveragejson.adoc[]
include::../requirements/requirements_class_zone_data_jpegxl.adoc[]
include::../requirements/requirements_class_zone_data_png.adoc[]
include::../requirements/requirements_class_zone_list_fgjson.adoc[]
include::../requirements/requirements_class_zone_list_geotiff.adoc[]
```

**Comment by jerstlouis** [comment]
Thanks for clarifying this @gbuehler . I'll fix these.

Do you think it's because of different versions of metanorma have different behavior in terms of which errors are fatal or not, that it did build on my end? ( and even sometimes on the auto-generated system? )

**Comment by ghobona** [comment]
@jerstlouis My guess is that the anchor `<<TIFF_V6>>` was copied from OGC API - Tiles - Part 1: Core.

If that is the case, then all you need to do is to copy and paste the TIFF reference from https://raw.githubusercontent.com/opengeospatial/ogcapi-tiles/master/core/standard/clause_3_references.adoc

**Comment by ghobona** [comment]
TIP: metanorma maintainers recommend to always place a blank line between successive `include::` statements.

**Comment by jerstlouis** [comment]
Thanks @ghobona  .

> My guess is that the anchor <<TIFF_V6>> was copied from OGC API - Tiles - Part 1: Core.

We just didn't set up those anchors yet. I would not expect this to be a fatal error that completely prevents generating the document (and it was not a fatal error when running metanorma locally).

> TIP: metanorma maintainers recommend to always place a blank line between successive include:: statements.

I always follow that recommendation! :) Much better relying on extra lines in the included documents.

**Comment by jerstlouis** [comment]
@gbuehler 

This commit:

https://github.com/opengeospatial/ogcapi-discrete-global-grid-systems/commit/d24661d64e53095bfaebf20350816660601cc424

should address those remaining issues.
